export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";

export const SET_PAYMENT_METHOD_SUCCESS = "SET_PAYMENT_METHOD_SUCCESS";

export const SET_CREDIT_CARD_NUMBER_SUCCESS = "SET_CREDIT_CARD_NUMBER_SUCCESS";

export const SET_STORE_SUCCESS = "SET_STORE_SUCCESS";
export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const SET_DELIVERY_TIME_SUCCESS = "SET_DELIVERY_TIME_SUCCESS";
export const SET_DELIVERY_DATE_SUCCESS = "SET_DELIVERY_DATE_SUCCESS";

export const GET_PRODUCT_PRIMARY_CATEGORY_LIST_SUCCESS =
  "GET_PRODUCT_PRIMARY_CATEGORY_LIST_SUCCESS";
export const GET_PRODUCT_SECONDARY_CATEGORY_LIST_SUCCESS =
  "GET_PRODUCT_SECONDARY_CATEGORY_LIST_SUCCESS";

export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";

export const GET_RECIPE_CATEGORY_SUCCESS = "GET_RECIPE_CATEGORY_SUCCESS";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const FETCH_RECIPE_LOADING_START = "FETCH_RECIPE_LOADING_START";
export const FETCH_RECIPE_LOADING_END = "FETCH_RECIPE_LOADING_END";

export const SET_LANGUAGE_SUCCESS = "SET_LANGUAGE_SUCCESS";
export const GET_VERIFICATION_CODE_SUCCESS = "GET_VERIFICATION_CODE_SUCCESS";
export const CHECK_VERIFICATION_CODE_SUCCESS =
  "CHECK_VERIFICATION_CODE_SUCCESS";

export const SET_CURRENT_LOCATION_SUCCESS = "SET_CURRENT_LOCATION_SUCCESS";

export const FETCH_VERIFICATIONCODE_RESULT_DATA_START =
  "FETCH_VERIFICATIONCODE_RESULT_DATA_START";

export const FETCH_GET_VERIFICATIONCODE_RESULT_DATA_END =
  "FETCH_GET_VERIFICATIONCODE_RESULT_DATA_END";

export const FETCH_CHECK_VERIFICATIONCODE_RESULT_DATA_START =
  "FETCH_CHECK_VERIFICATIONCODE_RESULT_DATA_START";

export const FETCH_CHECK_VERIFICATIONCODE_RESULT_DATA_END =
  "FETCH_CHECK_VERIFICATIONCODE_RESULT_DATA_END";

export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_SUCCESS_END = "UPDATE_USER_INFO_SUCCESS_END";

export const GET_COUPON_SUCCESS = "GET_COUPON_SUCCESS";

export const GET_CONTACT_US_SUCCESS = "GET_CONTACT_US_SUCCESS";

export const GET_SAVED_ITEM_SUCCESS = "GET_SAVED_ITEM_SUCCESS";
export const GET_SAVED_ITEM_SUCCESS_END = "GET_SAVED_ITEM_SUCCESS_END";

export const GET_PAYMENT_METHOD_SUCCESS = "GET_PAYMENT_METHOD_SUCCESS";
export const ADD_PAYMENT_METHOD_SUCCESS = "ADD_PAYMENT_METHOD_SUCCESS";

export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_SUCCESS_END = "ADD_ADDRESS_SUCCESS_END";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_SUCCESS_END = "DELETE_ADDRESS_SUCCESS_END";
export const SET_ADDRESS_DEFAULT_SUCCESS = "SET_ADDRESS_DEFAULT_SUCCESS";
export const SET_ADDRESS_GEOMETRY_SUCCESS = "SET_ADDRESS_GEOMETRY_SUCCESS";
export const SET_SELECTED_ADDRESS_SUCCESS = "SET_SELECTED_ADDRESS_SUCCESS";

export const GET_PRODUCT_LIST_SUCCESS_END = "GET_PRODUCT_LIST_SUCCESS_END";
export const ADD_PRODUCT_FAVORITE_SUCCESS = "ADD_PRODUCT_FAVORITE_SUCCESS";
export const GET_SUGGESTED_PRODUCT_SUCCESS = "GET_SUGGESTED_PRODUCT_SUCCESS";
export const SET_SELECTED_SECONDARY_CATEGORY_SUCCESS =
  "SET_SELECTED_SECONDARY_CATEGORY_SUCCESS";

export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_SUCCESS_END =
  "ADD_PRODUCT_TO_CART_SUCCESS_END";
export const GET_PRODUCT_FROM_CART_SUCCESS = "GET_PRODUCT_FROM_CART_SUCCESS";
export const GET_PRODUCT_PRICE_CART_SUCCESS = "GET_PRODUCT_PRICE_CART_SUCCESS";
export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const SET_DELIVER_ADDRESS = "SET_DELIVER_ADDRESS";
export const MAKE_ORDER_SUCCESS_END = "MAKE_ORDER_SUCCESS_END";

export const GET_FAVORITE_PRODUCT_SUCCESS = "GET_FAVORITE_PRODUCT_SUCCESS";
export const REMOVE_FAVORITE_PRODUCT_SUCCESS =
  "REMOVE_FAVORITE_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAVORITE_SUCCESS_END =
  "ADD_PRODUCT_FAVORITE_SUCCESS_END";
export const REMOVE_FAVORITE_PRODUCT_SUCCESS_END =
  "REMOVE_FAVORITE_PRODUCT_SUCCESS_END";

export const GET_HOME_PAGE_LAYOUT_SUCCESS = "GET_HOME_PAGE_LAYOUT_SUCCESS";

export const GET_RECOMMEND_SEARCH_SUCCESS = "GET_RECOMMEND_SEARCH_SUCCESS";
export const GET_HISTORY_SEARCH_SUCCESS = "GET_HISTORY_SEARCH_SUCCESS";
export const SEARCH_PRODUCT_BY_TEXT_SUCCESS = "SEARCH_PRODUCT_BY_TEXT_SUCCESS";

export const GET_RECIPE_DETAIL_SUCCESS = "GET_RECIPE_DETAIL_SUCCESS";
export const ADD_PAYMENT_METHOD_SUCCESS_END = "ADD_PAYMENT_METHOD_SUCCESS_END";

export const USE_COUPON_SUCCESS = "USE_COUPON_SUCCESS";
export const USE_COUPON_SUCCESS_END = "USE_COUPON_SUCCESS_END";
export const SET_SELECTED_COUPON_INFO = "SET_SELECTED_COUPON_INFO";

export const GET_PRODUCT_DETAIL_SUCCESS_END = "GET_PRODUCT_DETAIL_SUCCESS_END";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";
export const SET_CREDIT_CARD_ID_SUCCESS = "SET_CREDIT_CARD_ID_SUCCESS";

export const MAKE_ORDER_LOADING = "MAKE_ORDER_LOADING";
export const GET_PRODUCT_LIST_START = "GET_PRODUCT_LIST_START";
export const GET_PRODUCT_FROM_CART_START = "GET_PRODUCT_FROM_CART_START";
export const GET_PRODUCT_DETAIL_START = "GET_PRODUCT_DETAIL_START";
export const DELETE_PAYMENT_METHOD_END = "DELETE_PAYMENT_METHOD_END";
export const RESET_DELETE_PAYMENT_METHOD = "RESET_DELETE_PAYMENT_METHOD";
export const DELETE_PAYMENT_METHOD_START = "DELETE_PAYMENT_METHOD_START";
export const GET_RECIPE_CATEGORY_SUCCESS_END =
  "GET_RECIPE_CATEGORY_SUCCESS_END";
export const SEARCH_RECIPE_BY_TEXT_SUCCESS = "SEARCH_RECIPE_BY_TEXT_SUCCESS";
export const SET_STORE_SUCCESS_LOADING = "SET_STORE_SUCCESS_LOADING";
export const ADD_PRODUCT_TO_CART_SUCCESS_LOADING =
  "ADD_PRODUCT_TO_CART_SUCCESS_LOADING";
export const GET_ORDERS_SUCCESS_START = "GET_ORDERS_SUCCESS_START";
export const CHANGE_ORDERS_STATE_SUCCESS = "CHANGE_ORDERS_STATE_SUCCESS";
export const CHANGE_ORDERS_STATE_SUCCESS_START =
  "CHANGE_ORDERS_STATE_SUCCESS_START";
export const CHANGE_ORDERS_STATE_SUCCESS_END =
  "CHANGE_ORDERS_STATE_SUCCESS_END";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_SUCCESS_START = "ADD_REVIEW_SUCCESS_START";
export const GET_STORE_INFO_SUCCESS = "GET_STORE_INFO_SUCCESS";
export const GET_STORE_INFO_SUCCESS_START = "GET_STORE_INFO_SUCCESS_START";
export const GET_DRIVER_INFO_SUCCESS = "GET_DRIVER_INFO_SUCCESS";
export const GET_DRIVER_INFO_SUCCESS_START = "GET_DRIVER_INFO_SUCCESS_START";
export const ADD_REVIEW_SUCCESS_END = "ADD_REVIEW_SUCCESS_END";

export const THIRDPARTY_LOGIN = "THIRDPARTY_LOGIN";

export const MAKE_ORDER_PAY_BY_CREDITCARD_SUCCESS =
  "MAKE_ORDER_PAY_BY_CREDITCARD_SUCCESS";
export const RESET_MAKE_ORDER_PAY_BY_CREDITCARD_MESSAGE =
  "RESET_MAKE_ORDER_PAY_BY_CREDITCARD_MESSAGE";

export const GET_RECIPE_DETAIL_SUCCESS_START =
  "GET_RECIPE_DETAIL_SUCCESS_START";

export const ADD_PAYMENT_METHOD_SUCCESS_LOADING =
  "ADD_PAYMENT_METHOD_SUCCESS_LOADING";

export const SET_RECIPE_NAVIGATION_PARAMS = "SET_RECIPE_NAVIGATION_PARAMS";
export const SET_RECIPE_NAVIGATION_PARAMS_END =
  "SET_RECIPE_NAVIGATION_PARAMS_END";
export const SET_RECIPE_DETAIL_NAVIGATION_PARAMS =
  "SET_RECIPE_DETAIL_NAVIGATION_PARAMS";
export const SET_RECIPE_DETAIL_NAVIGATION_PARAMS_END =
  "SET_RECIPE_DETAIL_NAVIGATION_PARAMS_END";

export const RECHECKOUT_UPDATE_CART = "RECHECKOUT_UPDATE_CART";
export const RECHECKOUT_MAKE_ORDER = "RECHECKOUT_MAKE_ORDER";
export const RECHECKOUT_MAKE_ORDER_END = "RECHECKOUT_MAKE_ORDER_END";

export const GET_PRODUCT_SECONDARY_CATEGORY_LIST_SUCCESS_START =
  "GET_PRODUCT_SECONDARY_CATEGORY_LIST_SUCCESS_START";

export const GET_ALL_RECIPE_SUCCESS = "GET_ALL_RECIPE_SUCCESS";

export const CLEAR_REDUX_DELIVERY_TIME_DATE = "CLEAR_REDUX_DELIVERY_TIME_DATE";

export const MODIFY_RED_HEART_FLAG = "MODIFY_RED_HEART_FLAG";

export const SET_DELIVER_TYPE = "SET_DELIVER_TYPE";

export const SET_LOGIN_LOADING = "SET_LOGIN_LOADING";

export const GET_PRODUCT_PRICE_CART_START = "GET_PRODUCT_PRICE_CART_START";

export const GET_HOME_PAGE_LAYOUT_START = "GET_HOME_PAGE_LAYOUT_START";

export const SET_SEND_NOTIFICATION_FLAG_SUCCESS = "SET_SEND_NOTIFICATION_FLAG_SUCCESS";
